[package]
name = "fp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
pollster = "0.2"
rand_core = "0.6.4"
wgpu = { version = "0.15"}
env_logger = "0.10.0"

